language: objective-c
osx_image: xcode8
xcode_project: Animation.xcodeproj 
xcode_scheme: Animation
xcode_sdk: iphonesimulator10.0

script:
  - xcodebuild -project Animation.xcodeproj -scheme Animation -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' build test | xcpretty


